version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependency fix"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows" # Location of your action files
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/" # Location of your Dockerfile
    schedule:
      interval: "daily" 