name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install with DEV Dependencies
      uses: php-actions/composer@v6

    - name: PHP Static Analysis
      uses: php-actions/phpstan@v3
      with:
        level: 9
        path: src/

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      with:
        version: 9
        bootstrap: vendor/autoload.php
        configuration: tests/phpunit.xml
        args: --coverage-text

    - name: Cache Composer Packages
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      uses: php-actions/composer@v6
      with:
        only_args: --no-interaction --no-dev --ignore-platform-reqs --optimize-autoloader

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/samplesyncapp
        tags: |
             type=raw,value={{date 'YYYYMMDD'}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        sbom: true
        provenance: mode=max
        push: true
      #run: docker build . --file Dockerfile --tag samplesyncapp:$(date +%s)
