name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install with DEV dependencies
      uses: php-actions/composer@v6

    - name: PHP Static Analysis
      uses: php-actions/phpstan@v3
      with:
        level: 9
        path: src/

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      with:
        version: 9
        bootstrap: vendor/autoload.php
        configuration: tests/phpunit.xml
        args: --coverage-text

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        only_args: --no-interaction --no-dev --ignore-platform-reqs --optimize-autoloader